[project]
name = "akmi-utils"
version = "0.1.9.0"
authors = [
    {name = "Eko Indarto", email = "eko.indarto@dans.knaw.nl"}
]
description = "Utilities for AKMI integration and instrumentation (FastAPI helpers with OpenTelemetry and Prometheus support)."
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "dynaconf>=3.2.12",
    "fastapi>=0.120.0",
    "httpx>=0.28.1",
    "opentelemetry-distro>=0.59b0",
    "opentelemetry-exporter-otlp>=1.38.0",
    "opentelemetry-instrumentation-fastapi>=0.59b0",
    "opentelemetry-instrumentation-logging>=0.59b0",
    "prometheus-client>=0.23.1",
    "pyyaml>=6.0.3",
    "toml>=0.10.2",
    "tomli>=2.3.0",
    "uvicorn>=0.38.0",
]
